field.storage_settings.number_plate:
  type: mapping
  label: 'Number plate storage settings'
  mapping:
    number_max_length:
      type: integer
      label: 'Max length for the number'
    code_max_length:
      type: integer
      label: 'Max length for the code'

field.widget.settings.default_number_plate_widget:
  type: mapping
  label: 'Default number plate widget settings'
  mapping:
    number_size:
      type: integer
      label: 'Number size'
    code_size:
      type: integer
      label: 'Code size'
    fieldset_state:
      type: string
      label: 'The state of the fieldset which contains the two fields: open/closed'
    placeholder:
      type: mapping
      label: 'The placeholders for the two fields'
      mapping:
        number:
          type: string
          label: 'The placeholder for the number field'
        code:
          type: string
          label: 'The placeholder for the code field'
